### PR TITLE
🏇 Performance optimizations

### PR DESCRIPTION
**Pull request by canterberry**
Making optimizations one by one through Node.js profiling. See individual commits for details.

### CODE REVIEW

**Comment by canterberry** [comment]
Also in this PR: Remove Travis CI builds for Node.js versions that have EOL'ed, including v6 which reached its end-of-life yesterday.

**Comment by canterberry** [comment]
The few small revisions in this PR has led to ~75% reduction in hash time, based on my very limited benchmarks so far. On my machine, the benchmark went from about 1,000ms to about 250ms.

Still further benchmarks to be run, but overall I think it's a step in the right direction.

## Methodology

I used Node.js's built-in V8 profiling to analyze where time is spent while running the benchmark test.

```
# Produces a file named something like isolate-0x_______-____-v8.log
$ node --prof benchmark

# Processes the file generated in the previous step into human-readable form
$ node --prof-process isolate-0x_______-____-v8.log > benchmark.txt
```

This report looks something like:

```
Statistical profiling result from isolate-0x3dfc7f0-5276-v8.log, (204 ticks, 0 unaccounted, 0 excluded).

 [Shared libraries]:
   ticks  total  nonlib   name
     56   27.5%          /path/to/node
      4    2.0%          /lib/x86_64-linux-gnu/libc-2.27.so

 [JavaScript]:
   ticks  total  nonlib   name
     77   37.7%   53.5%  LazyCompile: *<anonymous> /path/to/node-sha3/lib/sponge/permute/index.js:1:515
     29   14.2%   20.1%  LazyCompile: *theta /path/to/node-sha3/lib/sponge/permute/theta/index.js:1:258
      2    1.0%    1.4%  LazyCompile: *rhoPi /path/to/node-sha3/lib/sponge/permute/rho-pi/index.js:1:388
      1    0.5%    0.7%  LazyCompile: *chi /path/to/node-sha3/lib/sponge/permute/chi/index.js:1:254
      1    0.5%    0.7%  LazyCompile: *byteLength buffer.js:488:20
      1    0.5%    0.7%  LazyCompile: *Sponge.squeeze /path/to/node-sha3/lib/sponge/index.js:1:1353
      1    0.5%    0.7%  LazyCompile: *FastBuffer internal/buffer.js:928:1
...
```

I would run through this, make some tweaks to the functions where the report indicates most of the time is being spent, run the test suite to make sure everything is still operational, then run the report and analyze the results. If I made things worse, I'd revert my changes and try something else. If I improved them, I'd run the following to sanity check that times have indeed improved:

```
$ for i in $(seq 1 10); do; time node benchmark; done
```

This produces output similar to the following:

```
node benchmark  0.27s user 0.03s system 123% cpu 0.238 total
node benchmark  0.25s user 0.02s system 125% cpu 0.215 total
node benchmark  0.24s user 0.03s system 125% cpu 0.217 total
node benchmark  0.27s user 0.01s system 126% cpu 0.223 total
node benchmark  0.25s user 0.02s system 124% cpu 0.213 total
node benchmark  0.27s user 0.01s system 125% cpu 0.224 total
node benchmark  0.26s user 0.02s system 126% cpu 0.217 total
node benchmark  0.25s user 0.02s system 125% cpu 0.217 total
node benchmark  0.27s user 0.01s system 127% cpu 0.219 total
node benchmark  0.25s user 0.02s system 123% cpu 0.222 total
```

If the times improved from the previous iteration and the number of *ticks* in the report has gone down, then I'd commit the result and repeat the process.

**Comment by canterberry** [comment]
In order to get a sense of how this benchmarks compared to the results in #44, I've replaced my local copy of **benchmark/index.js** with the following:

```
const { PerformanceObserver, performance } = require('perf_hooks');
const { Keccak } = require('../lib');
const inputBuffer = Buffer.allocUnsafe(4096);

inputBuffer.fill(0x42);

new PerformanceObserver((items) => {
  console.log(items.getEntries()[0].duration);
  performance.clearMarks();
}).observe({ entryTypes: ['measure'] });

performance.mark('before');
for (let i = 0; i < 1000; i++) {
  const keccak = new Keccak(256);
  keccak.update(inputBuffer);
  keccak.digest();
}
performance.mark('after');
performance.measure('duration', 'before', 'after');
```

Running this code against the current `master` build consistently gives me a duration of about **2,250ms**.

Running this same code against the this PR consistently gives me a duration of about **375ms** -- an **83%** reduction.

**Comment by canterberry** [comment]
## Benchmark: 10,000 iterations of "Hello, world!"

### js-sha3

```
$ for i in $(seq 1 10); do; time node js-sha3; done  
node js-sha3  0.17s user 0.03s system 114% cpu 0.174 total
node js-sha3  0.13s user 0.01s system 120% cpu 0.114 total
node js-sha3  0.13s user 0.01s system 119% cpu 0.119 total
node js-sha3  0.12s user 0.02s system 118% cpu 0.118 total
node js-sha3  0.14s user 0.01s system 122% cpu 0.122 total
node js-sha3  0.13s user 0.01s system 119% cpu 0.117 total
node js-sha3  0.12s user 0.02s system 118% cpu 0.119 total
node js-sha3  0.14s user 0.01s system 122% cpu 0.118 total
node js-sha3  0.14s user 0.01s system 119% cpu 0.125 total
node js-sha3  0.14s user 0.01s system 122% cpu 0.121 total
```

Runtime tends to be right around **125ms**.

### sha3 (PR #53)

```
$ for i in $(seq 1 10); do; time node sha3; done 
node sha3  0.34s user 0.06s system 121% cpu 0.331 total
node sha3  0.30s user 0.01s system 125% cpu 0.250 total
node sha3  0.27s user 0.03s system 125% cpu 0.245 total
node sha3  0.28s user 0.02s system 124% cpu 0.240 total
node sha3  0.28s user 0.02s system 124% cpu 0.242 total
node sha3  0.28s user 0.02s system 124% cpu 0.245 total
node sha3  0.31s user 0.05s system 115% cpu 0.305 total
node sha3  0.29s user 0.01s system 125% cpu 0.241 total
node sha3  0.30s user 0.01s system 126% cpu 0.242 total
node sha3  0.27s user 0.04s system 124% cpu 0.251 total
```

Runtime tends to be right around **250ms**, so only about **2x** slower than js-sha3.

### sha3 (2.0.1)

```
$ for i in $(seq 1 10); do; time node sha3; done
node sha3  1.13s user 0.05s system 115% cpu 1.029 total
node sha3  1.07s user 0.04s system 115% cpu 0.961 total
node sha3  1.07s user 0.05s system 116% cpu 0.962 total
node sha3  1.09s user 0.06s system 117% cpu 0.984 total
node sha3  1.08s user 0.04s system 117% cpu 0.953 total
node sha3  1.13s user 0.04s system 117% cpu 0.996 total
node sha3  1.08s user 0.05s system 116% cpu 0.975 total
node sha3  1.13s user 0.02s system 117% cpu 0.979 total
node sha3  1.15s user 0.04s system 115% cpu 1.024 total
node sha3  1.19s user 0.03s system 116% cpu 1.044 total
```

Runtime tends to be right around **1,000ms**, so about **8x** slower than js-sha3 (and **4x** slower than this PR).

## Benchmark: 1,000,000 iterations of "Hello, world!"

### js-sha3

```
$ for i in $(seq 1 10); do; time node js-sha3; done
node js-sha3  3.46s user 0.04s system 105% cpu 3.327 total
node js-sha3  3.35s user 0.03s system 102% cpu 3.306 total
node js-sha3  3.42s user 0.02s system 102% cpu 3.355 total
node js-sha3  3.52s user 0.02s system 104% cpu 3.384 total
node js-sha3  3.51s user 0.02s system 102% cpu 3.427 total
node js-sha3  3.47s user 0.02s system 103% cpu 3.366 total
node js-sha3  3.53s user 0.01s system 102% cpu 3.457 total
node js-sha3  3.45s user 0.02s system 102% cpu 3.392 total
node js-sha3  3.46s user 0.03s system 102% cpu 3.416 total
node js-sha3  3.54s user 0.02s system 103% cpu 3.436 total
```

Runtime tends to be around **3.4 seconds**.

### sha3 (PR #53)

```
$ for i in $(seq 1 10); do; time node sha3; done 
node sha3  13.57s user 0.11s system 101% cpu 13.460 total
node sha3  13.70s user 0.05s system 101% cpu 13.542 total
node sha3  13.25s user 0.03s system 101% cpu 13.104 total
node sha3  14.00s user 0.05s system 101% cpu 13.825 total
node sha3  13.95s user 0.05s system 101% cpu 13.761 total
node sha3  13.98s user 0.08s system 101% cpu 13.829 total
node sha3  13.98s user 0.04s system 101% cpu 13.798 total
node sha3  14.23s user 0.06s system 101% cpu 14.048 total
node sha3  14.40s user 0.07s system 101% cpu 14.220 total
node sha3  14.24s user 0.05s system 101% cpu 14.051 total
```

Runtime tends to be around **13.75 seconds**, which is about **4x** slower than js-sha3.

### sha3 (2.0.1)

```
$ for i in $(seq 1 10); do; time node sha3; done
node sha3  87.36s user 1.01s system 102% cpu 1:25.92 total
```

I only let this run through a single sample, which took about **85 seconds**, or **25x** slower than js-sha3 (and about **6x** slower than this PR).

## Conclusion

js-sha3 is an order of magnitude faster than any other pure JavaScript implementation so far, and this PR is an order of magnitude faster than v2.0.1 (the latest `master`).

If no objections, @davidmurdoch, I'll go ahead and merge this and release v2.0.2.

**Comment by canterberry** [comment]
Source code for benchmarks is here: https://github.com/canterberry/keccak-benchmarks.js

**Comment by davidmurdoch** [comment]
You may want to use something like [benchmark.js](https://github.com/bestiejs/benchmark.js/) which should give you statistically significant results. The performance progress is looking good so far. :+1:

**Comment by canterberry** [comment]
## Results using benchmark.js

```
js-sha3 0.0000035636763871388963
sha3@2.0.1 0.0000911752970183871
sha3@next 0.000013172918646467009
```

Using the latest from https://github.com/canterberry/keccak-benchmarks.js which uses benchmark.js, we can see that using js-sha3 as a baseline, this PR is slightly better than 4x slower than js-sha3, and about 7x faster than 2.0.1 (the current master branch of this library).

**Pull request merged**
