### PR TITLE
🎨Prepare for 1.2.1 release

### PR DESCRIPTION
**Pull request by canterberry**
Follow-up to #33 to prepare for publishing.

 * ⬆️ Upgrade `nan` and `mocha` packages to latest versions to address deprecation warnings during install process.
 * 🔧Add Node.js 8.11.1 (LTS), 9.11.1, and 10.0.0 to Travis CI configuration.
 * ⬆️Increment version for v1.2.1 release.

### CODE REVIEW

**Comment by canterberry** [comment]
cc @NoahHydro for review

**Comment by canterberry** [comment]
In order to unblock folks depending on #33, and since tests have passed on Travis CI, going ahead and merging this in to publish to npm. Will be monitoring for any Issues that may arise.

**Comment by NoahHydro** [comment]
Looks good to me! One thing to note: others seem to have implemented the NewInstance fix slightly differently. The changes seem comparable to me, but I'm no c++/v8 expert, so I'll [link that code](https://github.com/brave/node-sha3/commit/d44d293e997c061560c2bd8a41451ab979e5a4ca) here for the sake of transparency.

**Comment by canterberry** [comment]
Ah, well-spotted. Your implementation seems to have gotten us past the warnings and installation errors. Will look into the rationale behind the `cons->NewInstance` alternative to see if there's more to it than an aesthetic difference.

**Pull request merged**
