### PR TITLE
Sync missing documentation for SHAKE

### PR DESCRIPTION
**Pull request by septs**

### CODE REVIEW

**Review by canterberry — APPROVED** [review]
LGTM. Thank you!

**Comment by septs** [comment]
@canterberry CI is not working?

**Comment by canterberry** [comment]
Yeah, looks like Travis CI finally completed its decommissioning of the .org domain. I've started putting together a CircleCI pipeline and have entertained the notion of migrating to GitLab and have both in a functional state, but just not integrated here. It's been on the backburner until needed, and now it looks like the time has come!

**Review by canterberry — APPROVED** [review]

**Comment by canterberry** [comment]
Merged this without CI, given the innocuous documentation-only changes and the benefit of getting that shipped without waiting for the much more arduous CI remedy.

**Pull request merged**
